# configuration for "master" branch
# build in Release mode and deploy to Azure
-
  branches:
      only:
        - master
        - develop

  assembly_info:
    patch: false

  configuration: Release

  build_script:
    - ps: .\build.ps1

  deploy:
    provider: NuGet
    api_key:
      secure: L12xtuaeiigr5AHCfz0Qd3PrnssYxA1IC819hTmi+pxebwOFoZT4wQGYEq1C9lsH
    skip_symbols: false
    symbol_server:           # remove to push symbols to SymbolSource.org
    artifact: /.*\.nupkg/

  test: off
  skip_tags: true

  cache:
  - src\packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

# configuration for all branches except master
# build in Release mode but not deployed
-
  branches:
    except:
      - master
      - develop

  configuration: Release

  build_script:
    - ps: .\build.ps1

  test: off
  skip_tags: true

  cache:
    - src\packages -> **\packages.config  # preserve "packages" directory in the root of build folder but will reset it if packages.config is modified

# "fall back" configuration for all other branches
# no "branches" section defined
# do not deploy at all
-
  configuration: Debug
